version: '3'
services:
  db:
    image: postgres:11
    container_name: pgdatabase
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    #user: "${UID}:${GID}" # Linux users.
    volumes:
        - ./volumes/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  odoo:
    image: odoo:13
    container_name: odoo13
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
    tty: true
    command: -- -d ${DATABASE} --dev=reload
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - PYTHONDONTWRITEBYTECODE=1
    #user: "${UID}:${GID}" # Linux users.
    volumes:
      - ${ADDONS_PATH}:/mnt/extra-addons
      - ./volumes/odoo:/etc/odoo
      - /dev/shm:/dev/shm
    restart: always
