version: '3'
services:
  db:
    image: postgres:11
    container_name: ${ALIAS}_pgdatabase
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    #user: "${UID}:${GID}" # Linux users.
    volumes:
        - ${PG_PATH}:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  odoo:
    image: odoo:14.0
    container_name: ${ALIAS}_odoo14
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
    tty: true
    #command: -- -d ${DATABASE} --dev=reload
    command: -- --dev=reload
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - PYTHONDONTWRITEBYTECODE=1
    #user: "${UID}:${GID}" # Linux users.
    volumes:
      - ${ODOO_DATA_PATH}:/mnt/odoo-data
      - ${ODOO_EXTRA_ADDONS}:/mnt/extra-addons
      - ${ODOO_ENTERPRISE_ADDONS}:/mnt/enterprise-addons
      - ./volumes/odoo:/etc/odoo
      - /dev/shm:/dev/shm
    restart: always
