version: '3'
services:
  db:
    image: postgres:${PG_VERSION}
    container_name: ${ALIAS}_postgresql
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    #user: "${UID}:${GID}" # Linux users.
    volumes:
        - ${PG_PATH}:/var/lib/postgresql/data
        - ${PG_LOGS_PATH}:/logs
    ports:
      - "5432:5432"
    restart: always

  odoo:
    image: odoo:${ODOO_VERSION}
    container_name: ${ALIAS}_odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
    tty: true
    command: -- --dev=reload
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - PYTHONDONTWRITEBYTECODE=1
    #user: "${UID}:${GID}" # Linux users.
    volumes:
      - ${ODOO_DATA_PATH}:/mnt/odoo-data
      - ${ODOO_EXTRA_ADDONS}:/mnt/extra-addons
      - ${ODOO_ENTERPRISE_ADDONS}:/mnt/enterprise-addons
      - ./volumes/odoo:/etc/odoo
      - /dev/shm:/dev/shm
    restart: always
